instruction_def = {
    'Ask how to help.':0,
    'Greet.':1,
    'Ask name.':2,
    'Check reservation with name.':3,
    'Ask connection type.':4,
    'Ask origin and destination.':5,
    'Ask schedule.':6,
    'Ask schedule timing.':7,
    'Check flight table.':8,
    'Confirm booking.':9,
    'Confirm canceling.':10,
    'Ask additional requirements.':11,
    'Ask price condition.':12,
    'Agree with requirements.':13,
    'Finish session politely.':14,
    'Data Result':15,
}